### ISSUE TITLE
Nonexistent path in rc file

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/geos-chem#13]
Recently, the GMAO OPS $SHARE directory at NCCS was moved. As such, `/gpfsm/dnb52/projects/p10` does not exist. Looking around this repo, I found a few instances of it. Well, there were a *lot* of them in `run/GEOS/GEOSCHEMchem_ExtData.yaml` but it looks like @christophkeller took care of those in branches past `geos/develop`.

However, this one:

https://github.com/GEOS-ESM/geos-chem/blob/695fe485f00648532f1534d99ae9290c1229b2af/run/GEOS/GEOSCHEMchem_GridComp.rc#L229

seems to maybe still be around (I didn't check all branches). So, if someone on the team can check the current development code if it is, it should be updated to the generic `/discover/nobackup/projects/gmao/share` path.

**Comment by lizziel** [comment]
I am fixing this in the upstream GEOS-Chem and could make a PR for geos/develop and geos/latest_gcc at the same time. I'm using ~ewlundgr/bin/findreplace_p10_path.py to update all the config files.

**Comment by mathomp4** [comment]
Ahhh. Thanks @lizziel I figured something out there must have done it!
