### ISSUE TITLE
Before array is large and perhaps unused

### ISSUE THREAD

**Issue by obin1** [GEOS-ESM/geos-chem#17]
Lines 203-204 in `GeosCore/fullchem_mod.F90` declare a `Before` array
`    REAL(fp)               :: Before(State_Grid%NX, State_Grid%NY,           &
                                     State_Grid%NZ, State_Chm%nAdvect       )`

that seems like it could be a large array and might not be used anywhere in the module.  I've commented it out on my local version of geos/develop without any compilation issues, and could push those changes if Before isn't needed for something.

**Comment by viral211** [comment]
I agree with @obin1. @lizziel how would you like us to proceed?

**Comment by lizziel** [comment]
I checked the git history and the usage of the Before array was removed in 13.4.  Go ahead and delete. Thanks for catching this!

**Comment by obin1** [comment]
Okay great, I'll go ahead and delete the Before array. Thanks @lizziel and @viral211!
